//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cv_proje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCVENTITIYEntities2 : DbContext
    {
        public DBCVENTITIYEntities2()
            : base("name=DBCVENTITIYEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLadres> TBLadres { get; set; }
        public virtual DbSet<TBLcalismalarım> TBLcalismalarım { get; set; }
        public virtual DbSet<TBLhakkında> TBLhakkında { get; set; }
        public virtual DbSet<TBLiletişim> TBLiletişim { get; set; }
        public virtual DbSet<TBLyetenek> TBLyetenek { get; set; }
        public virtual DbSet<TBLadmin> TBLadmin { get; set; }
    }
}
