//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cv_proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLadres
    {
        public int id { get; set; }
        public string telefon { get; set; }
        public byte[] mail { get; set; }
        public byte[] adres { get; set; }
        public string konum { get; set; }
    }
}
