//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cv_proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLadmin
    {
        public int ıd { get; set; }
        public string kullanıcıadı { get; set; }
        public string sifre { get; set; }
    }
}
